const data = {
  products: [
    {
      _id: '1',
      name: 'nike slim shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High qualirty products',
    },
    {
      _id: '2',
      name: 'adidas slim shirt',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'nike',
      rating: 4.0,
      numReviews: 10,
      description: 'High qualirty products',
    },
    {
      _id: '3',
      name: 'lacoste free shirt',
      category: 'shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'High qualirty products',
    },
    {
      _id: '4',
      name: 'nike slim pants',
      category: 'pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 40,
      brand: 'Pants',
      rating: 4.5,
      numReviews: 14,
      description: 'High qualirty products',
    },
    {
      _id: '5',
      name: 'Puma slim shirt',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 23,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High qualirty products',
    },
    {
      _id: '6',
      name: 'adidas fit pant',
      category: 'shirts',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'High qualirty products',
    },
  ],
};

export default data;
